### PR TITLE
Support new configuration to define a connection timeout

### PR DESCRIPTION
**Pull request by gsdevme**
Support for https://github.com/usemarkup/contentful/pull/7

### CODE REVIEW

**Comment by shieldo** [comment]
I'd suggest we preserve BC and keep the config simple here, and just map this value down to both `timeout` Guzzle options.

**Comment by gsdevme** [comment]
I had thought about this, problem is some of the clients have 7 seconds, thats way too high to wait for a connection if you ask me?

**Comment by shieldo** [comment]
Though, you're changing an existing offered configuration option so it now has another meaning.  While this is probably OK in most cases this does constitute a BC break.

**Comment by gsdevme** [comment]
@shieldo changed this so the bundle will use the 'connection_timeout' for both Guzzles timeout & connection_timeout until we decide to add a breaking change and switch them around. 

(might want to squash, I edited it on Github)

**Comment by shieldo** [comment]
@gsdevme Looks good - will squash when merging 👍

**Pull request merged**
